# Generated by Django 3.2.3 on 2021-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_todo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
